stages:
  - build
  - test
  - integration-test
  - deploy

build:
  stage: build
  only:
    - merge_requests
    - main
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/litter-service"  
      --dockerfile "${CI_PROJECT_DIR}/litter-service/Dockerfile.production"
      --destination "${CI_REGISTRY_IMAGE}/litter:${CI_COMMIT_TAG:-latest}"
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/litter-client"  
      --dockerfile "${CI_PROJECT_DIR}/litter-client/Dockerfile.production"
      --destination "${CI_REGISTRY_IMAGE}/litter-client:${CI_COMMIT_TAG:-latest}"

lint-test-litter-client:
  stage: test
  image: node:18-alpine
  script:
    - cd litter-client
    - npm install
    - npm run lint

deploy-staging:
  stage: integration-test
  only:
    - merge_requests
    - main
  image:
    name: gcr.io/k8s-skaffold/skaffold:v2.0.0
    entrypoint: ['']
  environment:
    name: staging
    url: $LITTER_URL_STAGING # Set as environment variable. URL to your application. Ie HTTP://cscloud6-25.lnu.se
  script:
    - kubectl config get-contexts
   # Configure kubectl to use our own k8s cluster, you need to setup an Gitlab agent in you k8s kluster
    - kubectl config use-context $K8S_CONTEXT_STAGING
   # Authorize the cluster to pull images from our registry. (synced against Deploy Token "gitlab-deploy-token")
    - kubectl delete secret regcred || true
    - kubectl create secret docker-registry regcred --docker-server=$CI_REGISTRY --docker-username=$CI_DEPLOY_USER --docker-password=$CI_DEPLOY_PASSWORD

    - kubectl apply 
      -f ./k8s/litter-service.yaml
      -f ./k8s/litter-client.yaml
  
    - kubectl rollout restart deployment litter
    - kubectl rollout restart deployment litter-client
   # Debugging outputs after completion
    - kubectl get deployments
    - kubectl get pods
    - kubectl get services

deploy:
  stage: deploy
  only:
    - merge_requests
    - main
  image:
    name: gcr.io/k8s-skaffold/skaffold:v2.0.0
    entrypoint: ['']
  environment:
    name: production
    url: $LITTER_URL # Set as environment variable. URL to your application. Ie HTTP://cscloud6-25.lnu.se
  when: manual
  script:
    - kubectl config get-contexts
   # Configure kubectl to use our own k8s cluster, you need to setup an Gitlab agent in you k8s kluster
    - kubectl config use-context $K8S_CONTEXT
   # Authorize the cluster to pull images from our registry. (synced against Deploy Token "gitlab-deploy-token")
    - kubectl delete secret regcred || true
    - kubectl create secret docker-registry regcred --docker-server=$CI_REGISTRY --docker-username=$CI_DEPLOY_USER --docker-password=$CI_DEPLOY_PASSWORD

    - kubectl apply 
      -f ./k8s/litter-service.yaml
      -f ./k8s/litter-client.yaml

    - kubectl rollout restart deployment litter
    - kubectl rollout restart deployment litter-client
  
   # Debugging outputs after completion
    - kubectl get deployments
    - kubectl get pods
    - kubectl get services

