apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: litter
build:
  artifacts:
  - image: client
    context: litter-client
    docker:
      dockerfile: Dockerfile.production
  - image: lits
    context: lits-service
    docker:
      dockerfile: Dockerfile.production
deploy:
  kubectl:
    manifests:
      - ./k8s/ingress.yaml
      - ./k8s/litter-client.yaml
      - ./k8s/lits-service.yaml
      - ./k8s/mongodb-lits.yaml
