apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: litter
build:
  artifacts:
  - image: client
    context: litter-client
    docker:
      dockerfile: Dockerfile.production
deploy:
  kubectl:
    manifests:
      - ./k8s/ingress.yaml
      - ./k8s/litter-client.yaml
