apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: litter
build:
  artifacts:
  - image: litter
    context: litter-service
    docker:
      dockerfile: Dockerfile.production
  - image: auth-service
    context: auth-service
    docker:
      dockerfile: Dockerfile.production
deploy:
  kubectl:
    manifests:
      - ./k8s/ingress.yaml
      - ./k8s/litter-service.yaml
      - ./auth-service/k8s/auth-deployment.yaml
      - ./auth-service/k8s/auth-service.yaml
      - ./user-database/k8s/mongodb-service.yaml
      - ./user-database/k8s/mongodb-deployment.yaml
      - ./user-database/k8s/mongodb-pvc.yaml
      - ./user-database/k8s/mongodb-pv.yaml
