apiVersion: v1
kind: Service
metadata:
  labels:
    service.name: client
  name: client
spec:
  type: NodePort
  ports:
    - name: "client-port"
      port: 8888
      targetPort: 8080
  selector:
    deployment.name: client
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      deployment.name: client
  template:
    metadata:
      labels:
        deployment.name: client
    spec:
      containers:
      - name: client
        image: gitlab.lnu.se:5050/2dv013/student/team-2-bengal/litter/litter-client-staging:latest
        imagePullPolicy: Always
        env:
          - name: PORT
            value: "8080"
          - name: NODE_PORT
            value: "3000"
          - name: NODE_ENV
            value: "staging"
        ports:
          - containerPort: 8080
      #   volumeMounts:
      #     - name: nginx-config
      #       mountPath: /etc/nginx/
      # volumes:
      #   - name: nginx-config
      #     configMap:
      #       name: nginx-config      
      imagePullSecrets:
      - name: regcred
---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: nginx-config
#   namespace: default
# data:
#   nginx.conf: |
#     events {
#       worker_connections  1024;  ## Default
#     }

#     http {
#       server {
#         listen 8080;
#         listen [::]:8080;

#         root /usr/share/nginx/html;
#         index index.html;

#         location / {
#           try_files $uri /index.html;
#         }
#       }
#     }