apiVersion: v1
kind: Service
metadata:
  labels:
    service.name: auth-service
  name: auth-service
spec:
  type: NodePort
  ports:
    - name: "auth-service-port"
      port: 8888
      targetPort: 8080
  selector:
    deployment.name: auth-service
status:
  loadBalancer: {}
