apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    deployment.name: mongodb
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment.name: mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        deployment.name: mongodb
    spec:
      containers:
        - image: mongo:6.0.3
          name: mongodb
          ports:
            - containerPort: 27017
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-claim
      restartPolicy: Always
      volumes:
        - name: mongodb-claim
          persistentVolumeClaim:
            claimName: mongodb-claim
