apiVersion: v1
kind: Service
metadata:
  labels:
    service.name: mongodb
  name: mongodb
spec:
  type: ClusterIP
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    deployment.name: mongodb
status:
  loadBalancer: {}